name: "Deploy with Tencent CDN"
description: "Refresh Tencent CDN and deploy github pages to wiki.blocklynukkit.com"
author: superice666
runs:
  using: docker
  image: Dockerfile
branding:
  color: green
  icon: zap
